// <auto-generated />
using System;
using CRM.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CRM.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260619023757_AddConversationAndMessages")]
    partial class AddConversationAndMessages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CRM.Domain.Entities.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AudienceFilter")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RecurringDays")
                        .HasColumnType("text");

                    b.Property<string>("ScheduleType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SentCount")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("CRM.Domain.Entities.CampaignTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HtmlBody")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreviewUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CampaignTemplates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Simple white layout — great for updates and announcements.",
                            HtmlBody = "<!DOCTYPE html><html><head><meta charset=\"utf-8\">\n<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n<title>{{subject}}</title></head>\n<body style=\"margin:0;padding:0;background:#f4f4f4;font-family:'Helvetica Neue',Arial,sans-serif;\">\n<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\">\n<tr><td align=\"center\" style=\"padding:40px 16px;\">\n<table width=\"600\" cellpadding=\"0\" cellspacing=\"0\"\n  style=\"background:#ffffff;border-radius:10px;overflow:hidden;box-shadow:0 2px 12px rgba(0,0,0,.08);\">\n<tr><td>{{imageBlock}}</td></tr>\n<tr><td style=\"padding:48px 40px 32px;\">\n  <h1 style=\"margin:0 0 12px;font-size:30px;font-weight:700;color:#111827;line-height:1.2;\">{{title}}</h1>\n  <p style=\"margin:0 0 12px;font-size:13px;font-weight:600;color:#6366f1;text-transform:uppercase;letter-spacing:.08em;\">{{subject}}</p>\n  <hr style=\"border:none;border-top:1px solid #f0f0f0;margin:20px 0;\">\n  <div style=\"font-size:15px;color:#374151;line-height:1.75;\">{{description}}</div>\n</td></tr>\n<tr><td style=\"padding:24px 40px;background:#f9fafb;border-top:1px solid #e5e7eb;\">\n  <p style=\"margin:0;font-size:12px;color:#9ca3af;text-align:center;\">\n    You received this because you are a valued customer.&nbsp;\n    <a href=\"{{unsubscribeUrl}}\" style=\"color:#9ca3af;\">Unsubscribe</a>\n  </p>\n</td></tr>\n</table></td></tr></table>\n</body></html>",
                            Name = "Clean Minimal"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Eye-catching dark header with a prominent call-to-action — ideal for promotions.",
                            HtmlBody = "<!DOCTYPE html><html><head><meta charset=\"utf-8\">\n<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n<title>{{subject}}</title></head>\n<body style=\"margin:0;padding:0;background:#0f172a;font-family:'Helvetica Neue',Arial,sans-serif;\">\n<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\">\n<tr><td align=\"center\" style=\"padding:40px 16px;\">\n<table width=\"600\" cellpadding=\"0\" cellspacing=\"0\"\n  style=\"background:#1e293b;border-radius:12px;overflow:hidden;\">\n<tr><td style=\"padding:48px 40px 32px;text-align:center;\">\n  <p style=\"margin:0 0 16px;font-size:12px;font-weight:700;color:#818cf8;text-transform:uppercase;letter-spacing:.12em;\">{{subject}}</p>\n  <h1 style=\"margin:0 0 24px;font-size:36px;font-weight:800;color:#f8fafc;line-height:1.15;\">{{title}}</h1>\n</td></tr>\n<tr><td>{{imageBlock}}</td></tr>\n<tr><td style=\"padding:32px 40px;background:#0f172a;\">\n  <div style=\"font-size:15px;color:#94a3b8;line-height:1.8;margin-bottom:32px;\">{{description}}</div>\n  <div style=\"text-align:center;\">\n    <a href=\"#\" style=\"display:inline-block;background:linear-gradient(135deg,#6366f1,#8b5cf6);color:#fff;\n      text-decoration:none;padding:16px 40px;border-radius:8px;font-size:16px;font-weight:700;\n      letter-spacing:.02em;\">Get Started</a>\n  </div>\n</td></tr>\n<tr><td style=\"padding:20px 40px;text-align:center;\">\n  <p style=\"margin:0;font-size:12px;color:#475569;\">\n    <a href=\"{{unsubscribeUrl}}\" style=\"color:#475569;\">Unsubscribe</a>\n  </p>\n</td></tr>\n</table></td></tr></table>\n</body></html>",
                            Name = "Bold Promo"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Professional header, rich content section, and footer — perfect for newsletters.",
                            HtmlBody = "<!DOCTYPE html><html><head><meta charset=\"utf-8\">\n<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n<title>{{subject}}</title></head>\n<body style=\"margin:0;padding:0;background:#f3f4f6;font-family:'Helvetica Neue',Arial,sans-serif;\">\n<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\">\n<tr><td align=\"center\" style=\"padding:40px 16px;\">\n<table width=\"620\" cellpadding=\"0\" cellspacing=\"0\" style=\"background:#ffffff;border-radius:12px;overflow:hidden;\">\n<!-- Header -->\n<tr><td style=\"background:linear-gradient(135deg,#4f46e5 0%,#7c3aed 100%);padding:32px 40px;\">\n  <h2 style=\"margin:0;font-size:22px;font-weight:800;color:#ffffff;letter-spacing:-.01em;\">CRM Newsletter</h2>\n  <p style=\"margin:6px 0 0;font-size:13px;color:#c4b5fd;\">{{subject}}</p>\n</td></tr>\n<!-- Image -->\n<tr><td>{{imageBlock}}</td></tr>\n<!-- Content -->\n<tr><td style=\"padding:40px;\">\n  <h1 style=\"margin:0 0 16px;font-size:26px;font-weight:700;color:#111827;\">{{title}}</h1>\n  <div style=\"font-size:15px;color:#374151;line-height:1.8;\">{{description}}</div>\n</td></tr>\n<tr><td style=\"padding:0 40px 40px;\">\n  <hr style=\"border:none;border-top:1px solid #e5e7eb;margin:0 0 28px;\">\n  <p style=\"margin:0;font-size:13px;color:#6b7280;\">\n    Thanks for being part of our community. Reply to this email if you have any questions.\n  </p>\n</td></tr>\n<!-- Footer -->\n<tr><td style=\"padding:24px 40px;background:#f9fafb;border-top:1px solid #e5e7eb;\">\n  <p style=\"margin:0;font-size:12px;color:#9ca3af;text-align:center;\">\n    &copy; 2026 CRM System &bull;\n    <a href=\"{{unsubscribeUrl}}\" style=\"color:#9ca3af;\">Unsubscribe</a>\n  </p>\n</td></tr>\n</table></td></tr></table>\n</body></html>",
                            Name = "Newsletter"
                        });
                });

            modelBuilder.Entity("CRM.Domain.Entities.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid");

                    b.Property<int>("UnreadCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("CRM.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("AuthId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("CRM.Domain.Entities.MarketingHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InteractionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("MarketingHistories");
                });

            modelBuilder.Entity("CRM.Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenderRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedAgentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("CRM.Domain.Entities.Campaign", b =>
                {
                    b.HasOne("CRM.Domain.Entities.CampaignTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Template");
                });

            modelBuilder.Entity("CRM.Domain.Entities.MarketingHistory", b =>
                {
                    b.HasOne("CRM.Domain.Entities.Customer", "Customer")
                        .WithMany("MarketingHistories")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CRM.Domain.Entities.Message", b =>
                {
                    b.HasOne("CRM.Domain.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("CRM.Domain.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("CRM.Domain.Entities.Customer", b =>
                {
                    b.Navigation("MarketingHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
